basket_index:
    path:     /
    defaults: { _controller: "LilWorksStoreBundle:Basket:index" }
    methods:  GET

basket_show:
    path:     /{id}/show
    defaults: { _controller: "LilWorksStoreBundle:Basket:show" }
    methods:  GET

basket_new:
    path:     /new
    defaults: { _controller: "LilWorksStoreBundle:Basket:new" }
    methods:  [GET, POST]

basket_edit:
    path:     /{id}/edit
    defaults: { _controller: "LilWorksStoreBundle:Basket:edit" }
    methods:  [GET, POST]

basket_delete:
    path:     /{id}/delete
    defaults: { _controller: "LilWorksStoreBundle:Basket:delete" }
    methods:  [GET, POST]
