docfile_index:
    path:     /
    defaults: { _controller: "LilWorksStoreBundle:Docfile:index" }
    methods:  [GET, POST]

docfile_show:
    path:     /{docfile_id}/show
    defaults: { _controller: "LilWorksStoreBundle:Docfile:show" }
    methods:  GET

docfile_download:
    path:     /{docfile_id}/download
    defaults: { _controller: "LilWorksStoreBundle:Docfile:download" }
    methods:  GET
docfile_empty:
    path:     /{docfile_id}/empty
    defaults: { _controller: "LilWorksStoreBundle:Docfile:empty" }
    methods:  GET

docfile_new:
    path:     /new
    defaults: { _controller: "LilWorksStoreBundle:Docfile:new" }
    methods:  [GET, POST]

docfile_edit:
    path:     /{docfile_id}/edit
    defaults: { _controller: "LilWorksStoreBundle:Docfile:edit" }
    methods:  [GET, POST]

docfile_delete:
    path:     /{docfile_id}/delete
    defaults: { _controller: "LilWorksStoreBundle:Docfile:delete" }
    methods:  [GET, POST]
