realshippingmethod_index:
    path:     /
    defaults: { _controller: "LilWorksStoreBundle:RealShippingMethod:index" }
    methods:  [GET, POST]

realshippingmethod_show:
    path:     /{id}/show
    defaults: { _controller: "LilWorksStoreBundle:RealShippingMethod:show" }
    methods:  GET

realshippingmethod_new:
    path:     /new
    defaults: { _controller: "LilWorksStoreBundle:RealShippingMethod:new" }
    methods:  [GET, POST]

realshippingmethod_edit:
    path:     /{id}/edit
    defaults: { _controller: "LilWorksStoreBundle:RealShippingMethod:edit" }
    methods:  [GET, POST]

realshippingmethod_delete:
    path:     /{id}/delete
    defaults: { _controller: "LilWorksStoreBundle:RealShippingMethod:delete" }
    methods:  [GET, POST]
