storeinfo_index:
    path:     /
    defaults: { _controller: "LilWorksStoreBundle:StoreInfo:index" }
    methods:  GET

storeinfo_show:
    path:     /{id}/show
    defaults: { _controller: "LilWorksStoreBundle:StoreInfo:show" }
    methods:  GET

storeinfo_new:
    path:     /new
    defaults: { _controller: "LilWorksStoreBundle:StoreInfo:new" }
    methods:  [GET, POST]

storeinfo_edit:
    path:     /{id}/edit
    defaults: { _controller: "LilWorksStoreBundle:StoreInfo:edit" }
    methods:  [GET, POST]

storeinfo_delete:
    path:     /{id}/delete
    defaults: { _controller: "LilWorksStoreBundle:StoreInfo:delete" }
    methods:  [GET, POST]
