
lilworks_store:
    resource: "@LilWorksStoreBundle/Resources/config/routing.yml"
    prefix:   /store

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /app/

site:
    resource: "@SiteBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

lexik_translation_edition:
    resource: "@LexikTranslationBundle/Resources/config/routing.yml"
    prefix:   /translation

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"

lil_works_message:
    resource: "@LilworksMessageBundle/Resources/config/routing.yml"
    prefix:   /message