session_index:
    path:     /
    defaults: { _controller: "AppBundle:Session:index" }
    methods:  GET
session_clean:
    path:     /clean
    defaults: { _controller: "AppBundle:Session:clean" }
    methods:  GET

session_delete:
    path:     /{session_id}/detete
    defaults: { _controller: "AppBundle:Session:show" }
    methods:  GET





