user_index:
    path:     /
    defaults: { _controller: "AppBundle:User:index" }
    methods:  GET

user_show:
    path:     /{user_id}/show
    defaults: { _controller: "AppBundle:User:show" }
    methods:  GET

user_new:
    path:     /new
    defaults: { _controller: "AppBundle:User:new" }
    methods:  [GET, POST]

user_edit:
    path:     /{user_id}/edit
    defaults: { _controller: "AppBundle:User:edit" }
    methods:  [GET, POST]

user_delete:
    path:     /{user_id}/delete
    defaults: { _controller: "AppBundle:User:delete" }
    methods:  [GET, POST]
