<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20180401061759 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE lexik_trans_unit (id INT AUTO_INCREMENT NOT NULL, key_name VARCHAR(255) NOT NULL, domain VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX key_domain_idx (key_name, domain), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lexik_translation_file (id INT AUTO_INCREMENT NOT NULL, domain VARCHAR(255) NOT NULL, locale VARCHAR(10) NOT NULL, extention VARCHAR(10) NOT NULL, path VARCHAR(255) NOT NULL, hash VARCHAR(255) NOT NULL, UNIQUE INDEX hash_idx (hash), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lexik_trans_unit_translations (id INT AUTO_INCREMENT NOT NULL, file_id INT DEFAULT NULL, trans_unit_id INT DEFAULT NULL, locale VARCHAR(10) NOT NULL, content LONGTEXT NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_B0AA394493CB796C (file_id), INDEX IDX_B0AA3944C3C583C9 (trans_unit_id), UNIQUE INDEX trans_unit_locale_idx (trans_unit_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sessions (sess_id VARCHAR(128) NOT NULL, user INT DEFAULT NULL, basket INT DEFAULT NULL, sess_data LONGBLOB NOT NULL, sess_time INT DEFAULT NULL, sess_lifetime INT DEFAULT NULL, INDEX IDX_9A609D138D93D649 (user), UNIQUE INDEX UNIQ_9A609D132246507B (basket), PRIMARY KEY(sess_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fos_user (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(180) NOT NULL, username_canonical VARCHAR(180) NOT NULL, email VARCHAR(180) NOT NULL, email_canonical VARCHAR(180) NOT NULL, enabled TINYINT(1) NOT NULL, salt VARCHAR(255) DEFAULT NULL, password VARCHAR(255) NOT NULL, last_login DATETIME DEFAULT NULL, confirmation_token VARCHAR(180) DEFAULT NULL, password_requested_at DATETIME DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', UNIQUE INDEX UNIQ_957A647992FC23A8 (username_canonical), UNIQUE INDEX UNIQ_957A6479A0D96FBF (email_canonical), UNIQUE INDEX UNIQ_957A6479C05FB297 (confirmation_token), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_depositsales_paymentmethods (id INT AUTO_INCREMENT NOT NULL, coupon INT DEFAULT NULL, payedAt DATETIME DEFAULT NULL, amount DOUBLE PRECISION NOT NULL, description LONGTEXT DEFAULT NULL, depositSale INT NOT NULL, paymentMethod INT NOT NULL, INDEX IDX_508FE22464BF3F02 (coupon), INDEX IDX_508FE224DF3888AC (depositSale), INDEX IDX_508FE2248484E578 (paymentMethod), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_payment_method (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, tag VARCHAR(100) DEFAULT NULL, prefix VARCHAR(5) DEFAULT NULL, isPublished TINYINT(1) DEFAULT NULL, description LONGTEXT DEFAULT NULL, datas LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', pictureName VARCHAR(255) DEFAULT NULL, updatedAt DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_category (id INT AUTO_INCREMENT NOT NULL, isPublished TINYINT(1) DEFAULT NULL, pictureName VARCHAR(255) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, tag VARCHAR(100) NOT NULL, updatedAt DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_online_destocking (id INT AUTO_INCREMENT NOT NULL, destockedAt DATETIME DEFAULT NULL, destocking INT DEFAULT NULL, orderProduct INT DEFAULT NULL, UNIQUE INDEX UNIQ_8A3A5866264BCA67 (orderProduct), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_shipping_methods_countries (id INT AUTO_INCREMENT NOT NULL, country INT NOT NULL, price DOUBLE PRECISION DEFAULT NULL, freeTrigger DOUBLE PRECISION DEFAULT NULL, isPublished TINYINT(1) DEFAULT NULL, delay INT DEFAULT NULL, priority INT DEFAULT NULL, shippingMethod INT NOT NULL, INDEX IDX_8AADE823D520E70 (shippingMethod), INDEX IDX_8AADE825373C966 (country), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_warranty (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(50) NOT NULL, tag VARCHAR(50) NOT NULL, descriptionPublic TINYTEXT DEFAULT NULL, descriptionInternal TINYTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_product (id INT AUTO_INCREMENT NOT NULL, brand INT DEFAULT NULL, tag VARCHAR(100) NOT NULL, name VARCHAR(255) NOT NULL, isPublished TINYINT(1) DEFAULT NULL, description LONGTEXT DEFAULT NULL, descriptionInternal LONGTEXT DEFAULT NULL, priceOnline DOUBLE PRECISION DEFAULT NULL, priceOffline DOUBLE PRECISION DEFAULT NULL, priceBuying DOUBLE PRECISION DEFAULT NULL, priceRetail DOUBLE PRECISION DEFAULT NULL, leadTime VARCHAR(255) DEFAULT NULL, stock INT DEFAULT NULL, alwaysAvailable TINYINT(1) DEFAULT NULL, isSecondHand TINYINT(1) DEFAULT NULL, weight DOUBLE PRECISION DEFAULT NULL, width DOUBLE PRECISION DEFAULT NULL, length DOUBLE PRECISION DEFAULT NULL, height DOUBLE PRECISION DEFAULT NULL, isReviewable TINYINT(1) DEFAULT NULL, isArchived TINYINT(1) DEFAULT NULL, UNIQUE INDEX UNIQ_F9BA012B389B783 (tag), UNIQUE INDEX UNIQ_F9BA012B5E237E06 (name), INDEX IDX_F9BA012B1C52F958 (brand), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_products_categories (product_id INT NOT NULL, category_id INT NOT NULL, INDEX IDX_11925C904584665A (product_id), INDEX IDX_11925C9012469DE2 (category_id), PRIMARY KEY(product_id, category_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_products_tags (product_id INT NOT NULL, tag_id INT NOT NULL, INDEX IDX_501EF7084584665A (product_id), INDEX IDX_501EF708BAD26311 (tag_id), PRIMARY KEY(product_id, tag_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_products_shippingMethods (product_id INT NOT NULL, shippingmethod_id INT NOT NULL, INDEX IDX_33B31C204584665A (product_id), INDEX IDX_33B31C20ABA732A8 (shippingmethod_id), PRIMARY KEY(product_id, shippingmethod_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_products_warranties_offline (product_id INT NOT NULL, warranty_id INT NOT NULL, INDEX IDX_91E7C7B4584665A (product_id), INDEX IDX_91E7C7B2EC1782C (warranty_id), PRIMARY KEY(product_id, warranty_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_products_warranties_online (product_id INT NOT NULL, warranty_id INT NOT NULL, INDEX IDX_26CF064E4584665A (product_id), INDEX IDX_26CF064E2EC1782C (warranty_id), PRIMARY KEY(product_id, warranty_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_products_related_products (product INT NOT NULL, related_product INT NOT NULL, INDEX IDX_712A39C7D34A04AD (product), INDEX IDX_712A39C7EC53CE08 (related_product), PRIMARY KEY(product, related_product)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_products_taxesOnline (product_id INT NOT NULL, tax_id INT NOT NULL, INDEX IDX_8EB8FB3C4584665A (product_id), INDEX IDX_8EB8FB3CB2A824D8 (tax_id), PRIMARY KEY(product_id, tax_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_products_taxesOffline (product_id INT NOT NULL, tax_id INT NOT NULL, INDEX IDX_B7BD1B964584665A (product_id), INDEX IDX_B7BD1B96B2A824D8 (tax_id), PRIMARY KEY(product_id, tax_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_products_docfiles (product_id INT NOT NULL, docfile_id INT NOT NULL, INDEX IDX_2221D9B64584665A (product_id), INDEX IDX_2221D9B6E89F8343 (docfile_id), PRIMARY KEY(product_id, docfile_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_order (id INT AUTO_INCREMENT NOT NULL, seller INT DEFAULT NULL, customer INT DEFAULT NULL, reference VARCHAR(100) DEFAULT NULL, createdAt DATETIME DEFAULT NULL, updatedAt DATETIME DEFAULT NULL, userComment LONGTEXT DEFAULT NULL, storeComment LONGTEXT DEFAULT NULL, shippingAddressString LONGTEXT DEFAULT NULL, billingingAddressString LONGTEXT DEFAULT NULL, tot DOUBLE PRECISION DEFAULT NULL, payed DOUBLE PRECISION DEFAULT NULL, description LONGTEXT DEFAULT NULL, descriptionInternal LONGTEXT DEFAULT NULL, orderType INT DEFAULT NULL, billingAddress INT DEFAULT NULL, shippingAddress INT DEFAULT NULL, INDEX IDX_64DFCDDE22DCAE8D (orderType), INDEX IDX_64DFCDDEFB1AD3FC (seller), INDEX IDX_64DFCDDE81398E09 (customer), INDEX IDX_64DFCDDE7E1A92CE (billingAddress), INDEX IDX_64DFCDDE109A74D1 (shippingAddress), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_returns_paymentmethods (id INT AUTO_INCREMENT NOT NULL, coupon INT DEFAULT NULL, payedAt DATETIME DEFAULT NULL, amount DOUBLE PRECISION NOT NULL, description LONGTEXT DEFAULT NULL, orderProductReturn INT NOT NULL, paymentMethod INT NOT NULL, INDEX IDX_CDE8524664BF3F02 (coupon), INDEX IDX_CDE8524666B310CF (orderProductReturn), INDEX IDX_CDE852468484E578 (paymentMethod), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_orders_ordersteps (id INT AUTO_INCREMENT NOT NULL, order_id INT NOT NULL, createdAt DATETIME DEFAULT NULL, description LONGTEXT DEFAULT NULL, orderStep INT NOT NULL, INDEX IDX_741E17688D9F6D38 (order_id), INDEX IDX_741E1768EDBB0798 (orderStep), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_review (id INT AUTO_INCREMENT NOT NULL, product INT DEFAULT NULL, user INT DEFAULT NULL, rate INT DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, INDEX IDX_E66D933DD34A04AD (product), INDEX IDX_E66D933D8D93D649 (user), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_country (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, flag VARCHAR(255) DEFAULT NULL, tag VARCHAR(2) NOT NULL, isPublished TINYINT(1) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_address (id INT AUTO_INCREMENT NOT NULL, customer INT NOT NULL, country INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, companyName VARCHAR(255) DEFAULT NULL, street VARCHAR(255) DEFAULT NULL, complement VARCHAR(255) DEFAULT NULL, zipCode VARCHAR(255) NOT NULL, city VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, INDEX IDX_27BE6A0781398E09 (customer), INDEX IDX_27BE6A075373C966 (country), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_orders_realshippingmethods (id INT AUTO_INCREMENT NOT NULL, order_id INT DEFAULT NULL, price DOUBLE PRECISION DEFAULT NULL, reference LONGTEXT DEFAULT NULL, shippedAt DATETIME DEFAULT NULL, receivedAt DATETIME DEFAULT NULL, description LONGTEXT DEFAULT NULL, shippingMethod INT DEFAULT NULL, INDEX IDX_50C3F2FC8D9F6D38 (order_id), INDEX IDX_50C3F2FC3D520E70 (shippingMethod), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_orders_products (id INT AUTO_INCREMENT NOT NULL, order_id INT NOT NULL, product INT DEFAULT NULL, warranty_string VARCHAR(255) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, price DOUBLE PRECISION DEFAULT NULL, quantity INT DEFAULT NULL, description LONGTEXT DEFAULT NULL, serialNumber VARCHAR(255) DEFAULT NULL, isSecondHand TINYINT(1) DEFAULT NULL, destocking INT DEFAULT NULL, orderRealShippingMethod INT DEFAULT NULL, INDEX IDX_2D130ADA180330F1 (orderRealShippingMethod), INDEX IDX_2D130ADA8D9F6D38 (order_id), INDEX IDX_2D130ADAD34A04AD (product), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_ordersProducts_taxes (ordersproducts_id INT NOT NULL, tax_id INT NOT NULL, INDEX IDX_3631F956A036856 (ordersproducts_id), INDEX IDX_3631F95B2A824D8 (tax_id), PRIMARY KEY(ordersproducts_id, tax_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_order_products_warranties (ordersproducts_id INT NOT NULL, warranty_id INT NOT NULL, INDEX IDX_9B0332CD6A036856 (ordersproducts_id), INDEX IDX_9B0332CD2EC1782C (warranty_id), PRIMARY KEY(ordersproducts_id, warranty_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_tag (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) DEFAULT NULL, tag VARCHAR(100) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_order_product_return (id INT AUTO_INCREMENT NOT NULL, reference VARCHAR(20) NOT NULL, returnedAt DATETIME NOT NULL, isArchived TINYINT(1) DEFAULT NULL, quantity INT NOT NULL, description LONGTEXT DEFAULT NULL, orderProduct INT DEFAULT NULL, shippingMethod INT DEFAULT NULL, UNIQUE INDEX UNIQ_E402D7B4264BCA67 (orderProduct), INDEX IDX_E402D7B43D520E70 (shippingMethod), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_remoteUser (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(180) NOT NULL, username_canonical VARCHAR(180) NOT NULL, email VARCHAR(180) NOT NULL, email_canonical VARCHAR(180) NOT NULL, enabled TINYINT(1) NOT NULL, salt VARCHAR(255) DEFAULT NULL, password VARCHAR(255) NOT NULL, last_login DATETIME DEFAULT NULL, confirmation_token VARCHAR(180) DEFAULT NULL, password_requested_at DATETIME DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', remoteUserId VARCHAR(100) DEFAULT NULL, UNIQUE INDEX UNIQ_D924009E92FC23A8 (username_canonical), UNIQUE INDEX UNIQ_D924009EA0D96FBF (email_canonical), UNIQUE INDEX UNIQ_D924009EC05FB297 (confirmation_token), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_shipping_method (id INT AUTO_INCREMENT NOT NULL, pictureName VARCHAR(255) DEFAULT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, descriptionInternal LONGTEXT DEFAULT NULL, tag VARCHAR(100) NOT NULL, price DOUBLE PRECISION DEFAULT NULL, freeTrigger DOUBLE PRECISION DEFAULT NULL, delay INT DEFAULT NULL, isPublished TINYINT(1) DEFAULT NULL, priority INT DEFAULT NULL, createdAt DATETIME DEFAULT NULL, updatedAt DATETIME DEFAULT NULL, isNotReal TINYINT(1) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_baskets_realshippingmethods (id INT AUTO_INCREMENT NOT NULL, basket INT DEFAULT NULL, price DOUBLE PRECISION DEFAULT NULL, reference LONGTEXT DEFAULT NULL, shippingMethod INT DEFAULT NULL, INDEX IDX_CC85D4D2246507B (basket), INDEX IDX_CC85D4D3D520E70 (shippingMethod), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_supercategory (id INT AUTO_INCREMENT NOT NULL, tag VARCHAR(100) NOT NULL, name VARCHAR(255) NOT NULL, pos INT DEFAULT NULL, isPublished TINYINT(1) DEFAULT NULL, description LONGTEXT DEFAULT NULL, pictureName VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_customer (id INT AUTO_INCREMENT NOT NULL, user INT DEFAULT NULL, createdAt DATETIME DEFAULT NULL, remoteUser INT DEFAULT NULL, firstName VARCHAR(255) DEFAULT NULL, lastName VARCHAR(255) DEFAULT NULL, companyName VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_85C858198D93D649 (user), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_orderstep (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, tag VARCHAR(100) NOT NULL, description LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_basket (id INT AUTO_INCREMENT NOT NULL, user INT DEFAULT NULL, createdAt DATETIME DEFAULT NULL, updatedAt DATETIME DEFAULT NULL, tot DOUBLE PRECISION DEFAULT NULL, billingAddress INT DEFAULT NULL, shippingAddress INT DEFAULT NULL, paymentMethod INT DEFAULT NULL, INDEX IDX_BD6842808D93D649 (user), INDEX IDX_BD6842807E1A92CE (billingAddress), INDEX IDX_BD684280109A74D1 (shippingAddress), INDEX IDX_BD6842808484E578 (paymentMethod), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_orders_paymentmethods (id INT AUTO_INCREMENT NOT NULL, coupon INT DEFAULT NULL, order_id INT NOT NULL, payedAt DATETIME DEFAULT NULL, amount DOUBLE PRECISION NOT NULL, description LONGTEXT DEFAULT NULL, paymentMethod INT NOT NULL, INDEX IDX_6BA4931A64BF3F02 (coupon), INDEX IDX_6BA4931A8D9F6D38 (order_id), INDEX IDX_6BA4931A8484E578 (paymentMethod), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_tax (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, value DOUBLE PRECISION NOT NULL, type VARCHAR(10) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_docfile (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) DEFAULT NULL, description TINYTEXT DEFAULT NULL, docName VARCHAR(255) NOT NULL, docSize INT DEFAULT NULL, updatedAt DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_shipping_methods_triggers (id INT AUTO_INCREMENT NOT NULL, price DOUBLE PRECISION NOT NULL, shippingMethodTrigger DOUBLE PRECISION NOT NULL, shippingMethod INT DEFAULT NULL, INDEX IDX_C7DD89FA3D520E70 (shippingMethod), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_payment_modality (id INT AUTO_INCREMENT NOT NULL, modality VARCHAR(100) NOT NULL, isPublishedOnline TINYINT(1) DEFAULT NULL, isPublishedOffline TINYINT(1) DEFAULT NULL, description LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_store_info (id INT AUTO_INCREMENT NOT NULL, tag VARCHAR(255) NOT NULL, value LONGTEXT DEFAULT NULL, pictureName VARCHAR(255) NOT NULL, updatedAt DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_conversation (id INT AUTO_INCREMENT NOT NULL, user INT DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, conversationSubject VARCHAR(255) NOT NULL, sendmail TINYINT(1) DEFAULT NULL, isArchived TINYINT(1) DEFAULT NULL, unreaded INT DEFAULT NULL, createdAt DATETIME NOT NULL, INDEX IDX_59592C118D93D649 (user), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_shipping_methods_countries_triggers (id INT AUTO_INCREMENT NOT NULL, price DOUBLE PRECISION NOT NULL, shippingMethodCountryTrigger DOUBLE PRECISION NOT NULL, shippingMethodCountry INT DEFAULT NULL, INDEX IDX_74B28E87A3EFD76 (shippingMethodCountry), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_subscriber (id INT AUTO_INCREMENT NOT NULL, user INT DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, createdAt DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_88723A28E7927C74 (email), UNIQUE INDEX UNIQ_88723A288D93D649 (user), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_depositsale (id INT AUTO_INCREMENT NOT NULL, customer INT NOT NULL, status INT DEFAULT NULL, address INT DEFAULT NULL, product INT DEFAULT NULL, priceSelling DOUBLE PRECISION DEFAULT NULL, reference TINYTEXT DEFAULT NULL, priceBuying DOUBLE PRECISION NOT NULL, deposedAt DATE NOT NULL, selledAt DATE DEFAULT NULL, createdAt DATETIME DEFAULT NULL, description LONGTEXT DEFAULT NULL, descriptionInternal LONGTEXT DEFAULT NULL, serialNumber VARCHAR(255) DEFAULT NULL, INDEX IDX_7EF424F581398E09 (customer), INDEX IDX_7EF424F57B00651C (status), INDEX IDX_7EF424F5D4E6F81 (address), UNIQUE INDEX UNIQ_7EF424F5D34A04AD (product), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_annonce (id INT AUTO_INCREMENT NOT NULL, pictureName VARCHAR(255) DEFAULT NULL, tag VARCHAR(255) NOT NULL, name VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, isPublished TINYINT(1) DEFAULT NULL, pos INT DEFAULT NULL, link VARCHAR(100) DEFAULT NULL, updatedAt DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_conversation_message (id INT AUTO_INCREMENT NOT NULL, conversation INT DEFAULT NULL, createdAt DATETIME NOT NULL, readedAt DATETIME DEFAULT NULL, messageSubject VARCHAR(255) DEFAULT NULL, messageBody LONGTEXT NOT NULL, getCopy TINYINT(1) DEFAULT NULL, isResponse TINYINT(1) DEFAULT NULL, INDEX IDX_647B47DA8A8E26E9 (conversation), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_text_backup (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) DEFAULT NULL, content LONGTEXT DEFAULT NULL, css LONGTEXT DEFAULT NULL, updatedAt DATETIME DEFAULT NULL, createdAt DATETIME DEFAULT NULL, originalText INT DEFAULT NULL, INDEX IDX_2B824B38A317008D (originalText), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_phonenumber (id INT AUTO_INCREMENT NOT NULL, customer INT NOT NULL, phonenumber VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, INDEX IDX_EE0C85B581398E09 (customer), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_picture (id INT AUTO_INCREMENT NOT NULL, product INT DEFAULT NULL, pictureName VARCHAR(255) NOT NULL, pos INT DEFAULT NULL, description LONGTEXT DEFAULT NULL, updatedAt DATETIME NOT NULL, INDEX IDX_3C2B4A0FD34A04AD (product), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_coupon (id INT AUTO_INCREMENT NOT NULL, address INT DEFAULT NULL, customer INT NOT NULL, reference VARCHAR(100) NOT NULL, amount DOUBLE PRECISION NOT NULL, description LONGTEXT DEFAULT NULL, descriptionInternal LONGTEXT DEFAULT NULL, createdAt DATETIME DEFAULT NULL, validity DATETIME DEFAULT NULL, splitable TINYINT(1) DEFAULT NULL, isActive TINYINT(1) DEFAULT NULL, availableOnline TINYINT(1) DEFAULT NULL, INDEX IDX_FB912DF9D4E6F81 (address), INDEX IDX_FB912DF981398E09 (customer), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_baskets_products (id INT AUTO_INCREMENT NOT NULL, product INT DEFAULT NULL, basket INT DEFAULT NULL, quantity INT DEFAULT NULL, basketRealShippingMethod INT DEFAULT NULL, INDEX IDX_D14AEA97D34A04AD (product), INDEX IDX_D14AEA972246507B (basket), INDEX IDX_D14AEA97E3C1C7F4 (basketRealShippingMethod), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_brand (id INT AUTO_INCREMENT NOT NULL, pictureName VARCHAR(255) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, tag VARCHAR(100) NOT NULL, website VARCHAR(255) DEFAULT NULL, isPublished TINYINT(1) DEFAULT NULL, updatedAt DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_text (id INT AUTO_INCREMENT NOT NULL, tag VARCHAR(255) DEFAULT NULL, name VARCHAR(255) NOT NULL, title VARCHAR(255) DEFAULT NULL, content LONGTEXT DEFAULT NULL, css LONGTEXT DEFAULT NULL, updatedAt DATETIME DEFAULT NULL, exportInBase TINYINT(1) DEFAULT NULL, isContent TINYINT(1) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_ordertype (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, tag VARCHAR(100) NOT NULL, prefix VARCHAR(3) NOT NULL, destocking TINYINT(1) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_supercategories_categories (id INT AUTO_INCREMENT NOT NULL, supercategory INT NOT NULL, category INT NOT NULL, pos INT DEFAULT NULL, INDEX IDX_4B2955C3C0741010 (supercategory), INDEX IDX_4B2955C364C19C1 (category), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_depositsale_status (id INT AUTO_INCREMENT NOT NULL, name TINYTEXT NOT NULL, tag TINYTEXT NOT NULL, color TINYTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lilworks_message (id INT AUTO_INCREMENT NOT NULL, subject DATETIME NOT NULL, messageSubject LONGTEXT DEFAULT NULL, message LONGTEXT NOT NULL, response LONGTEXT DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, readed TINYINT(1) DEFAULT NULL, responseSended TINYINT(1) DEFAULT NULL, getCopy TINYINT(1) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE acl_classes (id INT UNSIGNED AUTO_INCREMENT NOT NULL, class_type VARCHAR(200) NOT NULL, UNIQUE INDEX UNIQ_69DD750638A36066 (class_type), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE acl_security_identities (id INT UNSIGNED AUTO_INCREMENT NOT NULL, identifier VARCHAR(200) NOT NULL, username TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_8835EE78772E836AF85E0677 (identifier, username), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE acl_object_identities (id INT UNSIGNED AUTO_INCREMENT NOT NULL, parent_object_identity_id INT UNSIGNED DEFAULT NULL, class_id INT UNSIGNED NOT NULL, object_identifier VARCHAR(100) NOT NULL, entries_inheriting TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_9407E5494B12AD6EA000B10 (object_identifier, class_id), INDEX IDX_9407E54977FA751A (parent_object_identity_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE acl_object_identity_ancestors (object_identity_id INT UNSIGNED NOT NULL, ancestor_id INT UNSIGNED NOT NULL, INDEX IDX_825DE2993D9AB4A6 (object_identity_id), INDEX IDX_825DE299C671CEA1 (ancestor_id), PRIMARY KEY(object_identity_id, ancestor_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE acl_entries (id INT UNSIGNED AUTO_INCREMENT NOT NULL, class_id INT UNSIGNED NOT NULL, object_identity_id INT UNSIGNED DEFAULT NULL, security_identity_id INT UNSIGNED NOT NULL, field_name VARCHAR(50) DEFAULT NULL, ace_order SMALLINT UNSIGNED NOT NULL, mask INT NOT NULL, granting TINYINT(1) NOT NULL, granting_strategy VARCHAR(30) NOT NULL, audit_success TINYINT(1) NOT NULL, audit_failure TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_46C8B806EA000B103D9AB4A64DEF17BCE4289BF4 (class_id, object_identity_id, field_name, ace_order), INDEX IDX_46C8B806EA000B103D9AB4A6DF9183C9 (class_id, object_identity_id, security_identity_id), INDEX IDX_46C8B806EA000B10 (class_id), INDEX IDX_46C8B8063D9AB4A6 (object_identity_id), INDEX IDX_46C8B806DF9183C9 (security_identity_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE lexik_trans_unit_translations ADD CONSTRAINT FK_B0AA394493CB796C FOREIGN KEY (file_id) REFERENCES lexik_translation_file (id)');
        $this->addSql('ALTER TABLE lexik_trans_unit_translations ADD CONSTRAINT FK_B0AA3944C3C583C9 FOREIGN KEY (trans_unit_id) REFERENCES lexik_trans_unit (id)');
        $this->addSql('ALTER TABLE sessions ADD CONSTRAINT FK_9A609D138D93D649 FOREIGN KEY (user) REFERENCES fos_user (id)');
        $this->addSql('ALTER TABLE sessions ADD CONSTRAINT FK_9A609D132246507B FOREIGN KEY (basket) REFERENCES lilworks_basket (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE lilworks_depositsales_paymentmethods ADD CONSTRAINT FK_508FE22464BF3F02 FOREIGN KEY (coupon) REFERENCES lilworks_coupon (id)');
        $this->addSql('ALTER TABLE lilworks_depositsales_paymentmethods ADD CONSTRAINT FK_508FE224DF3888AC FOREIGN KEY (depositSale) REFERENCES lilworks_depositsale (id)');
        $this->addSql('ALTER TABLE lilworks_depositsales_paymentmethods ADD CONSTRAINT FK_508FE2248484E578 FOREIGN KEY (paymentMethod) REFERENCES lilworks_payment_method (id)');
        $this->addSql('ALTER TABLE lilworks_online_destocking ADD CONSTRAINT FK_8A3A5866264BCA67 FOREIGN KEY (orderProduct) REFERENCES lilworks_orders_products (id)');
        $this->addSql('ALTER TABLE lilworks_shipping_methods_countries ADD CONSTRAINT FK_8AADE823D520E70 FOREIGN KEY (shippingMethod) REFERENCES lilworks_shipping_method (id)');
        $this->addSql('ALTER TABLE lilworks_shipping_methods_countries ADD CONSTRAINT FK_8AADE825373C966 FOREIGN KEY (country) REFERENCES lilworks_country (id)');
        $this->addSql('ALTER TABLE lilworks_product ADD CONSTRAINT FK_F9BA012B1C52F958 FOREIGN KEY (brand) REFERENCES lilworks_brand (id)');
        $this->addSql('ALTER TABLE lilworks_products_categories ADD CONSTRAINT FK_11925C904584665A FOREIGN KEY (product_id) REFERENCES lilworks_product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE lilworks_products_categories ADD CONSTRAINT FK_11925C9012469DE2 FOREIGN KEY (category_id) REFERENCES lilworks_category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE lilworks_products_tags ADD CONSTRAINT FK_501EF7084584665A FOREIGN KEY (product_id) REFERENCES lilworks_product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE lilworks_products_tags ADD CONSTRAINT FK_501EF708BAD26311 FOREIGN KEY (tag_id) REFERENCES lilworks_tag (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE lilworks_products_shippingMethods ADD CONSTRAINT FK_33B31C204584665A FOREIGN KEY (product_id) REFERENCES lilworks_product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE lilworks_products_shippingMethods ADD CONSTRAINT FK_33B31C20ABA732A8 FOREIGN KEY (shippingmethod_id) REFERENCES lilworks_shipping_method (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE lilworks_products_warranties_offline ADD CONSTRAINT FK_91E7C7B4584665A FOREIGN KEY (product_id) REFERENCES lilworks_product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE lilworks_products_warranties_offline ADD CONSTRAINT FK_91E7C7B2EC1782C FOREIGN KEY (warranty_id) REFERENCES lilworks_warranty (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE lilworks_products_warranties_online ADD CONSTRAINT FK_26CF064E4584665A FOREIGN KEY (product_id) REFERENCES lilworks_product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE lilworks_products_warranties_online ADD CONSTRAINT FK_26CF064E2EC1782C FOREIGN KEY (warranty_id) REFERENCES lilworks_warranty (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE lilworks_products_related_products ADD CONSTRAINT FK_712A39C7D34A04AD FOREIGN KEY (product) REFERENCES lilworks_product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE lilworks_products_related_products ADD CONSTRAINT FK_712A39C7EC53CE08 FOREIGN KEY (related_product) REFERENCES lilworks_product (id)');
        $this->addSql('ALTER TABLE lilworks_products_taxesOnline ADD CONSTRAINT FK_8EB8FB3C4584665A FOREIGN KEY (product_id) REFERENCES lilworks_product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE lilworks_products_taxesOnline ADD CONSTRAINT FK_8EB8FB3CB2A824D8 FOREIGN KEY (tax_id) REFERENCES lilworks_tax (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE lilworks_products_taxesOffline ADD CONSTRAINT FK_B7BD1B964584665A FOREIGN KEY (product_id) REFERENCES lilworks_product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE lilworks_products_taxesOffline ADD CONSTRAINT FK_B7BD1B96B2A824D8 FOREIGN KEY (tax_id) REFERENCES lilworks_tax (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE lilworks_products_docfiles ADD CONSTRAINT FK_2221D9B64584665A FOREIGN KEY (product_id) REFERENCES lilworks_product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE lilworks_products_docfiles ADD CONSTRAINT FK_2221D9B6E89F8343 FOREIGN KEY (docfile_id) REFERENCES lilworks_docfile (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE lilworks_order ADD CONSTRAINT FK_64DFCDDE22DCAE8D FOREIGN KEY (orderType) REFERENCES lilworks_ordertype (id)');
        $this->addSql('ALTER TABLE lilworks_order ADD CONSTRAINT FK_64DFCDDEFB1AD3FC FOREIGN KEY (seller) REFERENCES fos_user (id)');
        $this->addSql('ALTER TABLE lilworks_order ADD CONSTRAINT FK_64DFCDDE81398E09 FOREIGN KEY (customer) REFERENCES lilworks_customer (id)');
        $this->addSql('ALTER TABLE lilworks_order ADD CONSTRAINT FK_64DFCDDE7E1A92CE FOREIGN KEY (billingAddress) REFERENCES lilworks_address (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE lilworks_order ADD CONSTRAINT FK_64DFCDDE109A74D1 FOREIGN KEY (shippingAddress) REFERENCES lilworks_address (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE lilworks_returns_paymentmethods ADD CONSTRAINT FK_CDE8524664BF3F02 FOREIGN KEY (coupon) REFERENCES lilworks_coupon (id)');
        $this->addSql('ALTER TABLE lilworks_returns_paymentmethods ADD CONSTRAINT FK_CDE8524666B310CF FOREIGN KEY (orderProductReturn) REFERENCES lilworks_order_product_return (id)');
        $this->addSql('ALTER TABLE lilworks_returns_paymentmethods ADD CONSTRAINT FK_CDE852468484E578 FOREIGN KEY (paymentMethod) REFERENCES lilworks_payment_method (id)');
        $this->addSql('ALTER TABLE lilworks_orders_ordersteps ADD CONSTRAINT FK_741E17688D9F6D38 FOREIGN KEY (order_id) REFERENCES lilworks_order (id)');
        $this->addSql('ALTER TABLE lilworks_orders_ordersteps ADD CONSTRAINT FK_741E1768EDBB0798 FOREIGN KEY (orderStep) REFERENCES lilworks_orderstep (id)');
        $this->addSql('ALTER TABLE lilworks_review ADD CONSTRAINT FK_E66D933DD34A04AD FOREIGN KEY (product) REFERENCES lilworks_product (id)');
        $this->addSql('ALTER TABLE lilworks_review ADD CONSTRAINT FK_E66D933D8D93D649 FOREIGN KEY (user) REFERENCES fos_user (id)');
        $this->addSql('ALTER TABLE lilworks_address ADD CONSTRAINT FK_27BE6A0781398E09 FOREIGN KEY (customer) REFERENCES lilworks_customer (id)');
        $this->addSql('ALTER TABLE lilworks_address ADD CONSTRAINT FK_27BE6A075373C966 FOREIGN KEY (country) REFERENCES lilworks_country (id)');
        $this->addSql('ALTER TABLE lilworks_orders_realshippingmethods ADD CONSTRAINT FK_50C3F2FC8D9F6D38 FOREIGN KEY (order_id) REFERENCES lilworks_order (id)');
        $this->addSql('ALTER TABLE lilworks_orders_realshippingmethods ADD CONSTRAINT FK_50C3F2FC3D520E70 FOREIGN KEY (shippingMethod) REFERENCES lilworks_shipping_method (id)');
        $this->addSql('ALTER TABLE lilworks_orders_products ADD CONSTRAINT FK_2D130ADA180330F1 FOREIGN KEY (orderRealShippingMethod) REFERENCES lilworks_orders_realshippingmethods (id)');
        $this->addSql('ALTER TABLE lilworks_orders_products ADD CONSTRAINT FK_2D130ADA8D9F6D38 FOREIGN KEY (order_id) REFERENCES lilworks_order (id)');
        $this->addSql('ALTER TABLE lilworks_orders_products ADD CONSTRAINT FK_2D130ADAD34A04AD FOREIGN KEY (product) REFERENCES lilworks_product (id)');
        $this->addSql('ALTER TABLE lilworks_ordersProducts_taxes ADD CONSTRAINT FK_3631F956A036856 FOREIGN KEY (ordersproducts_id) REFERENCES lilworks_orders_products (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE lilworks_ordersProducts_taxes ADD CONSTRAINT FK_3631F95B2A824D8 FOREIGN KEY (tax_id) REFERENCES lilworks_tax (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE lilworks_order_products_warranties ADD CONSTRAINT FK_9B0332CD6A036856 FOREIGN KEY (ordersproducts_id) REFERENCES lilworks_orders_products (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE lilworks_order_products_warranties ADD CONSTRAINT FK_9B0332CD2EC1782C FOREIGN KEY (warranty_id) REFERENCES lilworks_warranty (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE lilworks_order_product_return ADD CONSTRAINT FK_E402D7B4264BCA67 FOREIGN KEY (orderProduct) REFERENCES lilworks_orders_products (id)');
        $this->addSql('ALTER TABLE lilworks_order_product_return ADD CONSTRAINT FK_E402D7B43D520E70 FOREIGN KEY (shippingMethod) REFERENCES lilworks_shipping_method (id)');
        $this->addSql('ALTER TABLE lilworks_baskets_realshippingmethods ADD CONSTRAINT FK_CC85D4D2246507B FOREIGN KEY (basket) REFERENCES lilworks_basket (id)');
        $this->addSql('ALTER TABLE lilworks_baskets_realshippingmethods ADD CONSTRAINT FK_CC85D4D3D520E70 FOREIGN KEY (shippingMethod) REFERENCES lilworks_shipping_method (id)');
        $this->addSql('ALTER TABLE lilworks_customer ADD CONSTRAINT FK_85C858198D93D649 FOREIGN KEY (user) REFERENCES fos_user (id)');
        $this->addSql('ALTER TABLE lilworks_basket ADD CONSTRAINT FK_BD6842808D93D649 FOREIGN KEY (user) REFERENCES fos_user (id)');
        $this->addSql('ALTER TABLE lilworks_basket ADD CONSTRAINT FK_BD6842807E1A92CE FOREIGN KEY (billingAddress) REFERENCES lilworks_address (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE lilworks_basket ADD CONSTRAINT FK_BD684280109A74D1 FOREIGN KEY (shippingAddress) REFERENCES lilworks_address (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE lilworks_basket ADD CONSTRAINT FK_BD6842808484E578 FOREIGN KEY (paymentMethod) REFERENCES lilworks_payment_method (id)');
        $this->addSql('ALTER TABLE lilworks_orders_paymentmethods ADD CONSTRAINT FK_6BA4931A64BF3F02 FOREIGN KEY (coupon) REFERENCES lilworks_coupon (id)');
        $this->addSql('ALTER TABLE lilworks_orders_paymentmethods ADD CONSTRAINT FK_6BA4931A8D9F6D38 FOREIGN KEY (order_id) REFERENCES lilworks_order (id)');
        $this->addSql('ALTER TABLE lilworks_orders_paymentmethods ADD CONSTRAINT FK_6BA4931A8484E578 FOREIGN KEY (paymentMethod) REFERENCES lilworks_payment_method (id)');
        $this->addSql('ALTER TABLE lilworks_shipping_methods_triggers ADD CONSTRAINT FK_C7DD89FA3D520E70 FOREIGN KEY (shippingMethod) REFERENCES lilworks_shipping_method (id)');
        $this->addSql('ALTER TABLE lilworks_conversation ADD CONSTRAINT FK_59592C118D93D649 FOREIGN KEY (user) REFERENCES fos_user (id)');
        $this->addSql('ALTER TABLE lilworks_shipping_methods_countries_triggers ADD CONSTRAINT FK_74B28E87A3EFD76 FOREIGN KEY (shippingMethodCountry) REFERENCES lilworks_shipping_methods_countries (id)');
        $this->addSql('ALTER TABLE lilworks_subscriber ADD CONSTRAINT FK_88723A288D93D649 FOREIGN KEY (user) REFERENCES fos_user (id)');
        $this->addSql('ALTER TABLE lilworks_depositsale ADD CONSTRAINT FK_7EF424F581398E09 FOREIGN KEY (customer) REFERENCES lilworks_customer (id)');
        $this->addSql('ALTER TABLE lilworks_depositsale ADD CONSTRAINT FK_7EF424F57B00651C FOREIGN KEY (status) REFERENCES lilworks_depositsale_status (id)');
        $this->addSql('ALTER TABLE lilworks_depositsale ADD CONSTRAINT FK_7EF424F5D4E6F81 FOREIGN KEY (address) REFERENCES lilworks_address (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE lilworks_depositsale ADD CONSTRAINT FK_7EF424F5D34A04AD FOREIGN KEY (product) REFERENCES lilworks_product (id)');
        $this->addSql('ALTER TABLE lilworks_conversation_message ADD CONSTRAINT FK_647B47DA8A8E26E9 FOREIGN KEY (conversation) REFERENCES lilworks_conversation (id)');
        $this->addSql('ALTER TABLE lilworks_text_backup ADD CONSTRAINT FK_2B824B38A317008D FOREIGN KEY (originalText) REFERENCES lilworks_text (id)');
        $this->addSql('ALTER TABLE lilworks_phonenumber ADD CONSTRAINT FK_EE0C85B581398E09 FOREIGN KEY (customer) REFERENCES lilworks_customer (id)');
        $this->addSql('ALTER TABLE lilworks_picture ADD CONSTRAINT FK_3C2B4A0FD34A04AD FOREIGN KEY (product) REFERENCES lilworks_product (id)');
        $this->addSql('ALTER TABLE lilworks_coupon ADD CONSTRAINT FK_FB912DF9D4E6F81 FOREIGN KEY (address) REFERENCES lilworks_address (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE lilworks_coupon ADD CONSTRAINT FK_FB912DF981398E09 FOREIGN KEY (customer) REFERENCES lilworks_customer (id)');
        $this->addSql('ALTER TABLE lilworks_baskets_products ADD CONSTRAINT FK_D14AEA97D34A04AD FOREIGN KEY (product) REFERENCES lilworks_product (id)');
        $this->addSql('ALTER TABLE lilworks_baskets_products ADD CONSTRAINT FK_D14AEA972246507B FOREIGN KEY (basket) REFERENCES lilworks_basket (id)');
        $this->addSql('ALTER TABLE lilworks_baskets_products ADD CONSTRAINT FK_D14AEA97E3C1C7F4 FOREIGN KEY (basketRealShippingMethod) REFERENCES lilworks_baskets_realshippingmethods (id)');
        $this->addSql('ALTER TABLE lilworks_supercategories_categories ADD CONSTRAINT FK_4B2955C3C0741010 FOREIGN KEY (supercategory) REFERENCES lilworks_supercategory (id)');
        $this->addSql('ALTER TABLE lilworks_supercategories_categories ADD CONSTRAINT FK_4B2955C364C19C1 FOREIGN KEY (category) REFERENCES lilworks_category (id)');
        $this->addSql('ALTER TABLE acl_object_identities ADD CONSTRAINT FK_9407E54977FA751A FOREIGN KEY (parent_object_identity_id) REFERENCES acl_object_identities (id)');
        $this->addSql('ALTER TABLE acl_object_identity_ancestors ADD CONSTRAINT FK_825DE2993D9AB4A6 FOREIGN KEY (object_identity_id) REFERENCES acl_object_identities (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE acl_object_identity_ancestors ADD CONSTRAINT FK_825DE299C671CEA1 FOREIGN KEY (ancestor_id) REFERENCES acl_object_identities (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE acl_entries ADD CONSTRAINT FK_46C8B806EA000B10 FOREIGN KEY (class_id) REFERENCES acl_classes (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE acl_entries ADD CONSTRAINT FK_46C8B8063D9AB4A6 FOREIGN KEY (object_identity_id) REFERENCES acl_object_identities (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE acl_entries ADD CONSTRAINT FK_46C8B806DF9183C9 FOREIGN KEY (security_identity_id) REFERENCES acl_security_identities (id) ON UPDATE CASCADE ON DELETE CASCADE');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE lexik_trans_unit_translations DROP FOREIGN KEY FK_B0AA3944C3C583C9');
        $this->addSql('ALTER TABLE lexik_trans_unit_translations DROP FOREIGN KEY FK_B0AA394493CB796C');
        $this->addSql('ALTER TABLE sessions DROP FOREIGN KEY FK_9A609D138D93D649');
        $this->addSql('ALTER TABLE lilworks_order DROP FOREIGN KEY FK_64DFCDDEFB1AD3FC');
        $this->addSql('ALTER TABLE lilworks_review DROP FOREIGN KEY FK_E66D933D8D93D649');
        $this->addSql('ALTER TABLE lilworks_customer DROP FOREIGN KEY FK_85C858198D93D649');
        $this->addSql('ALTER TABLE lilworks_basket DROP FOREIGN KEY FK_BD6842808D93D649');
        $this->addSql('ALTER TABLE lilworks_conversation DROP FOREIGN KEY FK_59592C118D93D649');
        $this->addSql('ALTER TABLE lilworks_subscriber DROP FOREIGN KEY FK_88723A288D93D649');
        $this->addSql('ALTER TABLE lilworks_depositsales_paymentmethods DROP FOREIGN KEY FK_508FE2248484E578');
        $this->addSql('ALTER TABLE lilworks_returns_paymentmethods DROP FOREIGN KEY FK_CDE852468484E578');
        $this->addSql('ALTER TABLE lilworks_basket DROP FOREIGN KEY FK_BD6842808484E578');
        $this->addSql('ALTER TABLE lilworks_orders_paymentmethods DROP FOREIGN KEY FK_6BA4931A8484E578');
        $this->addSql('ALTER TABLE lilworks_products_categories DROP FOREIGN KEY FK_11925C9012469DE2');
        $this->addSql('ALTER TABLE lilworks_supercategories_categories DROP FOREIGN KEY FK_4B2955C364C19C1');
        $this->addSql('ALTER TABLE lilworks_shipping_methods_countries_triggers DROP FOREIGN KEY FK_74B28E87A3EFD76');
        $this->addSql('ALTER TABLE lilworks_products_warranties_offline DROP FOREIGN KEY FK_91E7C7B2EC1782C');
        $this->addSql('ALTER TABLE lilworks_products_warranties_online DROP FOREIGN KEY FK_26CF064E2EC1782C');
        $this->addSql('ALTER TABLE lilworks_order_products_warranties DROP FOREIGN KEY FK_9B0332CD2EC1782C');
        $this->addSql('ALTER TABLE lilworks_products_categories DROP FOREIGN KEY FK_11925C904584665A');
        $this->addSql('ALTER TABLE lilworks_products_tags DROP FOREIGN KEY FK_501EF7084584665A');
        $this->addSql('ALTER TABLE lilworks_products_shippingMethods DROP FOREIGN KEY FK_33B31C204584665A');
        $this->addSql('ALTER TABLE lilworks_products_warranties_offline DROP FOREIGN KEY FK_91E7C7B4584665A');
        $this->addSql('ALTER TABLE lilworks_products_warranties_online DROP FOREIGN KEY FK_26CF064E4584665A');
        $this->addSql('ALTER TABLE lilworks_products_related_products DROP FOREIGN KEY FK_712A39C7D34A04AD');
        $this->addSql('ALTER TABLE lilworks_products_related_products DROP FOREIGN KEY FK_712A39C7EC53CE08');
        $this->addSql('ALTER TABLE lilworks_products_taxesOnline DROP FOREIGN KEY FK_8EB8FB3C4584665A');
        $this->addSql('ALTER TABLE lilworks_products_taxesOffline DROP FOREIGN KEY FK_B7BD1B964584665A');
        $this->addSql('ALTER TABLE lilworks_products_docfiles DROP FOREIGN KEY FK_2221D9B64584665A');
        $this->addSql('ALTER TABLE lilworks_review DROP FOREIGN KEY FK_E66D933DD34A04AD');
        $this->addSql('ALTER TABLE lilworks_orders_products DROP FOREIGN KEY FK_2D130ADAD34A04AD');
        $this->addSql('ALTER TABLE lilworks_depositsale DROP FOREIGN KEY FK_7EF424F5D34A04AD');
        $this->addSql('ALTER TABLE lilworks_picture DROP FOREIGN KEY FK_3C2B4A0FD34A04AD');
        $this->addSql('ALTER TABLE lilworks_baskets_products DROP FOREIGN KEY FK_D14AEA97D34A04AD');
        $this->addSql('ALTER TABLE lilworks_orders_ordersteps DROP FOREIGN KEY FK_741E17688D9F6D38');
        $this->addSql('ALTER TABLE lilworks_orders_realshippingmethods DROP FOREIGN KEY FK_50C3F2FC8D9F6D38');
        $this->addSql('ALTER TABLE lilworks_orders_products DROP FOREIGN KEY FK_2D130ADA8D9F6D38');
        $this->addSql('ALTER TABLE lilworks_orders_paymentmethods DROP FOREIGN KEY FK_6BA4931A8D9F6D38');
        $this->addSql('ALTER TABLE lilworks_shipping_methods_countries DROP FOREIGN KEY FK_8AADE825373C966');
        $this->addSql('ALTER TABLE lilworks_address DROP FOREIGN KEY FK_27BE6A075373C966');
        $this->addSql('ALTER TABLE lilworks_order DROP FOREIGN KEY FK_64DFCDDE7E1A92CE');
        $this->addSql('ALTER TABLE lilworks_order DROP FOREIGN KEY FK_64DFCDDE109A74D1');
        $this->addSql('ALTER TABLE lilworks_basket DROP FOREIGN KEY FK_BD6842807E1A92CE');
        $this->addSql('ALTER TABLE lilworks_basket DROP FOREIGN KEY FK_BD684280109A74D1');
        $this->addSql('ALTER TABLE lilworks_depositsale DROP FOREIGN KEY FK_7EF424F5D4E6F81');
        $this->addSql('ALTER TABLE lilworks_coupon DROP FOREIGN KEY FK_FB912DF9D4E6F81');
        $this->addSql('ALTER TABLE lilworks_orders_products DROP FOREIGN KEY FK_2D130ADA180330F1');
        $this->addSql('ALTER TABLE lilworks_online_destocking DROP FOREIGN KEY FK_8A3A5866264BCA67');
        $this->addSql('ALTER TABLE lilworks_ordersProducts_taxes DROP FOREIGN KEY FK_3631F956A036856');
        $this->addSql('ALTER TABLE lilworks_order_products_warranties DROP FOREIGN KEY FK_9B0332CD6A036856');
        $this->addSql('ALTER TABLE lilworks_order_product_return DROP FOREIGN KEY FK_E402D7B4264BCA67');
        $this->addSql('ALTER TABLE lilworks_products_tags DROP FOREIGN KEY FK_501EF708BAD26311');
        $this->addSql('ALTER TABLE lilworks_returns_paymentmethods DROP FOREIGN KEY FK_CDE8524666B310CF');
        $this->addSql('ALTER TABLE lilworks_shipping_methods_countries DROP FOREIGN KEY FK_8AADE823D520E70');
        $this->addSql('ALTER TABLE lilworks_products_shippingMethods DROP FOREIGN KEY FK_33B31C20ABA732A8');
        $this->addSql('ALTER TABLE lilworks_orders_realshippingmethods DROP FOREIGN KEY FK_50C3F2FC3D520E70');
        $this->addSql('ALTER TABLE lilworks_order_product_return DROP FOREIGN KEY FK_E402D7B43D520E70');
        $this->addSql('ALTER TABLE lilworks_baskets_realshippingmethods DROP FOREIGN KEY FK_CC85D4D3D520E70');
        $this->addSql('ALTER TABLE lilworks_shipping_methods_triggers DROP FOREIGN KEY FK_C7DD89FA3D520E70');
        $this->addSql('ALTER TABLE lilworks_baskets_products DROP FOREIGN KEY FK_D14AEA97E3C1C7F4');
        $this->addSql('ALTER TABLE lilworks_supercategories_categories DROP FOREIGN KEY FK_4B2955C3C0741010');
        $this->addSql('ALTER TABLE lilworks_order DROP FOREIGN KEY FK_64DFCDDE81398E09');
        $this->addSql('ALTER TABLE lilworks_address DROP FOREIGN KEY FK_27BE6A0781398E09');
        $this->addSql('ALTER TABLE lilworks_depositsale DROP FOREIGN KEY FK_7EF424F581398E09');
        $this->addSql('ALTER TABLE lilworks_phonenumber DROP FOREIGN KEY FK_EE0C85B581398E09');
        $this->addSql('ALTER TABLE lilworks_coupon DROP FOREIGN KEY FK_FB912DF981398E09');
        $this->addSql('ALTER TABLE lilworks_orders_ordersteps DROP FOREIGN KEY FK_741E1768EDBB0798');
        $this->addSql('ALTER TABLE sessions DROP FOREIGN KEY FK_9A609D132246507B');
        $this->addSql('ALTER TABLE lilworks_baskets_realshippingmethods DROP FOREIGN KEY FK_CC85D4D2246507B');
        $this->addSql('ALTER TABLE lilworks_baskets_products DROP FOREIGN KEY FK_D14AEA972246507B');
        $this->addSql('ALTER TABLE lilworks_products_taxesOnline DROP FOREIGN KEY FK_8EB8FB3CB2A824D8');
        $this->addSql('ALTER TABLE lilworks_products_taxesOffline DROP FOREIGN KEY FK_B7BD1B96B2A824D8');
        $this->addSql('ALTER TABLE lilworks_ordersProducts_taxes DROP FOREIGN KEY FK_3631F95B2A824D8');
        $this->addSql('ALTER TABLE lilworks_products_docfiles DROP FOREIGN KEY FK_2221D9B6E89F8343');
        $this->addSql('ALTER TABLE lilworks_conversation_message DROP FOREIGN KEY FK_647B47DA8A8E26E9');
        $this->addSql('ALTER TABLE lilworks_depositsales_paymentmethods DROP FOREIGN KEY FK_508FE224DF3888AC');
        $this->addSql('ALTER TABLE lilworks_depositsales_paymentmethods DROP FOREIGN KEY FK_508FE22464BF3F02');
        $this->addSql('ALTER TABLE lilworks_returns_paymentmethods DROP FOREIGN KEY FK_CDE8524664BF3F02');
        $this->addSql('ALTER TABLE lilworks_orders_paymentmethods DROP FOREIGN KEY FK_6BA4931A64BF3F02');
        $this->addSql('ALTER TABLE lilworks_product DROP FOREIGN KEY FK_F9BA012B1C52F958');
        $this->addSql('ALTER TABLE lilworks_text_backup DROP FOREIGN KEY FK_2B824B38A317008D');
        $this->addSql('ALTER TABLE lilworks_order DROP FOREIGN KEY FK_64DFCDDE22DCAE8D');
        $this->addSql('ALTER TABLE lilworks_depositsale DROP FOREIGN KEY FK_7EF424F57B00651C');
        $this->addSql('ALTER TABLE acl_entries DROP FOREIGN KEY FK_46C8B806EA000B10');
        $this->addSql('ALTER TABLE acl_entries DROP FOREIGN KEY FK_46C8B806DF9183C9');
        $this->addSql('ALTER TABLE acl_object_identities DROP FOREIGN KEY FK_9407E54977FA751A');
        $this->addSql('ALTER TABLE acl_object_identity_ancestors DROP FOREIGN KEY FK_825DE2993D9AB4A6');
        $this->addSql('ALTER TABLE acl_object_identity_ancestors DROP FOREIGN KEY FK_825DE299C671CEA1');
        $this->addSql('ALTER TABLE acl_entries DROP FOREIGN KEY FK_46C8B8063D9AB4A6');
        $this->addSql('DROP TABLE lexik_trans_unit');
        $this->addSql('DROP TABLE lexik_translation_file');
        $this->addSql('DROP TABLE lexik_trans_unit_translations');
        $this->addSql('DROP TABLE sessions');
        $this->addSql('DROP TABLE fos_user');
        $this->addSql('DROP TABLE lilworks_depositsales_paymentmethods');
        $this->addSql('DROP TABLE lilworks_payment_method');
        $this->addSql('DROP TABLE lilworks_category');
        $this->addSql('DROP TABLE lilworks_online_destocking');
        $this->addSql('DROP TABLE lilworks_shipping_methods_countries');
        $this->addSql('DROP TABLE lilworks_warranty');
        $this->addSql('DROP TABLE lilworks_product');
        $this->addSql('DROP TABLE lilworks_products_categories');
        $this->addSql('DROP TABLE lilworks_products_tags');
        $this->addSql('DROP TABLE lilworks_products_shippingMethods');
        $this->addSql('DROP TABLE lilworks_products_warranties_offline');
        $this->addSql('DROP TABLE lilworks_products_warranties_online');
        $this->addSql('DROP TABLE lilworks_products_related_products');
        $this->addSql('DROP TABLE lilworks_products_taxesOnline');
        $this->addSql('DROP TABLE lilworks_products_taxesOffline');
        $this->addSql('DROP TABLE lilworks_products_docfiles');
        $this->addSql('DROP TABLE lilworks_order');
        $this->addSql('DROP TABLE lilworks_returns_paymentmethods');
        $this->addSql('DROP TABLE lilworks_orders_ordersteps');
        $this->addSql('DROP TABLE lilworks_review');
        $this->addSql('DROP TABLE lilworks_country');
        $this->addSql('DROP TABLE lilworks_address');
        $this->addSql('DROP TABLE lilworks_orders_realshippingmethods');
        $this->addSql('DROP TABLE lilworks_orders_products');
        $this->addSql('DROP TABLE lilworks_ordersProducts_taxes');
        $this->addSql('DROP TABLE lilworks_order_products_warranties');
        $this->addSql('DROP TABLE lilworks_tag');
        $this->addSql('DROP TABLE lilworks_order_product_return');
        $this->addSql('DROP TABLE lilworks_remoteUser');
        $this->addSql('DROP TABLE lilworks_shipping_method');
        $this->addSql('DROP TABLE lilworks_baskets_realshippingmethods');
        $this->addSql('DROP TABLE lilworks_supercategory');
        $this->addSql('DROP TABLE lilworks_customer');
        $this->addSql('DROP TABLE lilworks_orderstep');
        $this->addSql('DROP TABLE lilworks_basket');
        $this->addSql('DROP TABLE lilworks_orders_paymentmethods');
        $this->addSql('DROP TABLE lilworks_tax');
        $this->addSql('DROP TABLE lilworks_docfile');
        $this->addSql('DROP TABLE lilworks_shipping_methods_triggers');
        $this->addSql('DROP TABLE lilworks_payment_modality');
        $this->addSql('DROP TABLE lilworks_store_info');
        $this->addSql('DROP TABLE lilworks_conversation');
        $this->addSql('DROP TABLE lilworks_shipping_methods_countries_triggers');
        $this->addSql('DROP TABLE lilworks_subscriber');
        $this->addSql('DROP TABLE lilworks_depositsale');
        $this->addSql('DROP TABLE lilworks_annonce');
        $this->addSql('DROP TABLE lilworks_conversation_message');
        $this->addSql('DROP TABLE lilworks_text_backup');
        $this->addSql('DROP TABLE lilworks_phonenumber');
        $this->addSql('DROP TABLE lilworks_picture');
        $this->addSql('DROP TABLE lilworks_coupon');
        $this->addSql('DROP TABLE lilworks_baskets_products');
        $this->addSql('DROP TABLE lilworks_brand');
        $this->addSql('DROP TABLE lilworks_text');
        $this->addSql('DROP TABLE lilworks_ordertype');
        $this->addSql('DROP TABLE lilworks_supercategories_categories');
        $this->addSql('DROP TABLE lilworks_depositsale_status');
        $this->addSql('DROP TABLE lilworks_message');
        $this->addSql('DROP TABLE acl_classes');
        $this->addSql('DROP TABLE acl_security_identities');
        $this->addSql('DROP TABLE acl_object_identities');
        $this->addSql('DROP TABLE acl_object_identity_ancestors');
        $this->addSql('DROP TABLE acl_entries');
    }
}
