<?php

namespace LilWorks\StoreBundle\Entity\Repository;

/**
 * BrandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandRepository  extends \Doctrine\ORM\EntityRepository
{
    public function paginatorQueryBuilder($filter = '')
    {


        $qbc = $this->createQueryBuilder('p');
        $qbc
            ->from('LilWorksStoreBundle:Brand','b')
            ->leftJoin('LilWorksStoreBundle:Product','pr','WITH','pr.brand = p.id')
            ->groupBy("p.id")
            ->andHaving('p.name LIKE :filter OR p.website LIKE :filter')
            ->setParameter('filter', '%'.$filter.'%');

        $count = count($qbc->getQuery()->getScalarResult());

        $em = $this->getEntityManager();

        $qb = $em->createQuery('
              SELECT b as brand , count(pr) as productsCount FROM LilWorksStoreBundle:Brand b
              LEFT JOIN LilWorksStoreBundle:Product pr WITH  pr.brand = b.id
              GROUP BY b.id
              HAVING  b.name LIKE :filter OR b.website LIKE :filter
              ')

            ->setParameter('filter', '%'.$filter.'%')
            ->setHint('knp_paginator.count', $count);


        return $qb;


    }
    public function getProductsIsPublished()
    {
        return 1;

    }
}
