<?php

namespace LilWorks\StoreBundle\Entity\Repository;

/**
 * CouponRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CouponRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNextReference($coupon){

        $prefix = $this->getEntityManager()->getRepository("LilWorksStoreBundle:PaymentMethod")->findOneByTag("COUPON")->getPrefix();
        if(!$prefix)
            return null;

        $year = ($coupon->getCreatedAt()) ? $coupon->getCreatedAt()->format('Y') : date('Y') ;

        $qb = $this->createQueryBuilder('c');
        $qb
            ->select('c.reference')
            ->where('c.reference LIKE :filter')
            ->setParameter('filter', $year.'-'.$prefix.'%');

        $results = $qb->getQuery()->getScalarResult();
        if(count($results)>0){
            $values = array();
            foreach($results as $result){
                array_push($values,intval(str_replace( $year.'-'.$prefix ,"",$result["reference"] ))) ;
            }
            rsort($values);
            $nextIndex = $values[0]+1;
        }else{
            $nextIndex = 1;
        }

        $zeroLeft = 4 - count($nextIndex);
        for($i=0;$i<$zeroLeft;$i++){
            $nextIndex =  "0" . $nextIndex;
        }

        return "$year-$prefix$nextIndex";

    }
}
