<?php

namespace LilWorks\StoreBundle\Entity\Repository;

/**
 * DepositSaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepositSaleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNextReference($depositSale){

        $prefix = "DV";

        $year = ($depositSale->getCreatedAt()) ? $depositSale->getCreatedAt()->format('Y') : date('Y') ;

        $qb = $this->createQueryBuilder('ds');
        $qb
            ->select('ds.reference')
            ->where('ds.reference LIKE :filter')
            ->setParameter('filter', $year.'-'.$prefix.'%');

        $results = $qb->getQuery()->getScalarResult();
        if(count($results)>0){
            $values = array();
            foreach($results as $result){
                array_push($values,intval(str_replace( $year.'-'.$prefix ,"",$result["reference"] ))) ;
            }
            rsort($values);
            $nextIndex = $values[0]+1;
        }else{
            $nextIndex = 1;
        }

        $zeroLeft = 4 - count($nextIndex);
        for($i=0;$i<$zeroLeft;$i++){
            $nextIndex =  "0" . $nextIndex;
        }

        return "$year-$prefix$nextIndex";

    }
}
