<?php

namespace LilWorks\StoreBundle\Entity\Repository;

/**
 * SuperCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuperCategoryRepository extends \Doctrine\ORM\EntityRepository
{

}
